<div class="header-container">
	<div class="header">
		<div class="for-full-withmenu">
            <div class="col-custommenu">
                <div class="custommenu-navigation">
			        <?php echo $this->getChildHtml("top.navigation.sections"); ?>
                </div>
                <div class="custommenu-toggle">
                    <div class="custommenu-title"><?php echo __('Menu');?></div>
                    <div class="toggle-icon">
                        <div class="toggle one"></div>
                        <div class="toggle two"></div>
                        <div class="toggle three"></div>
                    </div>
                </div>
            </div>
            <div class="col-logo"><?php echo $this->getChildHtml("logo"); ?></div>
			<div class="actions-header">				
                <?php echo $this->getChildHtml("currency"); ?>		
				<?php echo $this->getChildHtml("topSearch"); ?>	
				<div class="wishlist hidden-xs">
					<a href="<?php echo $this->getUrl('wishlist');?>"><i class="icon-heart"></i></a>
				</div>		
                <div class="register-login hidden-xs">
					<?php if(!$this->helper('Rokanthemes\Themeoption\Helper\Data')->isLoggedIn()){?>
						<a href="<?php echo $this->getUrl('customer/account/login');?>"><i class="icon-users"></i><?php echo __('Login');?></a>
					<?php
					}
					else{
					?>
					<a href="<?php echo $this->getUrl('customer/account/index');?>"><i class="icon-users"></i><?php echo __('My account');?></a>
					<?php } ?>
				</div>
				<?php echo $this->getChildHtml("minicart");?>
			</div>
		</div>
	</div>
</div>
<script type="text/javascript">
    require(['jquery'],function($){
        $(document).ready(function($){
            <?php if($this->helper('Rokanthemes\Themeoption\Helper\Themeconfig')->isEnableStickyHeader()){ ?>
			$(window).scroll(function() {
				var num = $('.header-container').outerHeight();
				var screenWidth = $(window).width();
				if ($(this).scrollTop() > num && screenWidth >= 768 ){  
					$(".header").addClass("sticky");
				}
				else{
					$(".header").removeClass("sticky");
				}
			});
            <?php } ?>
            $('.col-custommenu .toggle-icon').unbind("click").on( "click", function() {                
                if ($('.col-custommenu').hasClass('active')) {
                    $('.col-custommenu').removeClass('active');
                }else{
                    $('.col-custommenu').addClass('active');
                }
            });
            $( "li.ui-menu-item" ).mouseenter(function() {
                var image = $( this ).data( "image" );
                if (image) {
                    if ($( this ).hasClass('level0')) {
                        if ($( this ).hasClass('fullwidth')) {
                            $( this ).find('.image-categoty-menu .image').attr("src", image);
                        }
                    } else {
                        $( this ).closest('.level0').find('.image-categoty-menu .image').attr("src", image);
                    }
                }else{
                    var image_main = $( this ).closest('.level0').find('.level1').data( "image" );
                    if(image_main){
                        $( this ).closest('.level0').find('.image-categoty-menu .image').attr("src", image_main);
                    }
                }
            });
		});
    });
</script>